# Generated by Django 5.1.3 on 2024-12-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_description_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rag_status',
            field=models.CharField(choices=[('Red', 'Red'), ('Amber', 'Amber'), ('Green', 'Green')], default='Green', max_length=6),
        ),
    ]
