# Generated by Django 5.1.3 on 2024-12-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_rag_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
    ]
